### ISSUE TITLE
how to registrate normal color image, or grayscale image

### ISSUE THREAD

**Issue by dzz416** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#11]

**Comment by cwmok** [comment]
Hi @dzz416, 

Currently, this repository only supports 3D grayscale (single-channel) images. If you are looking for a learning-based method that supports 2D grayscale images, you may check out our latest work at https://github.com/cwmok/Conditional_LapIRN. We have created a 2D example. 

Alternatively, you may also check out the great VoxelMorph framework at https://github.com/voxelmorph/voxelmorph. They have a lot of tutorials for medical image registration, and their framework supports 2D registration as well.
