### ISSUE TITLE
training time is too long

### ISSUE THREAD

**Issue by celi7** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#15]
How many epochs did you set when training 255 volumes in your experiment? And how long does it take?
When I was training my own data, I found that the training time was too long. It took about 2 to 3 days for 20 volumes(144*80*16) with 1000 epochs. Is this normal?

**Comment by cwmok** [comment]
Hi @hcy5,

We train the model for fixed 150000 iterations. It takes 2-3 days for our machine.
Your training time is reasonable.

Compare to Voxelmorph, the most expensive operation (in terms of time complexity) is the scaling and squaring layer and we need to compute 4 scaling and squaring in each forward pass.

**Comment by celi7** [comment]
@cwmok 
Thank you for your reply and explaination!
