### ISSUE TITLE
The deformed grid not so smooth

### ISSUE THREAD

**Issue by xiaorugao999** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#16]
Hi, @cwmok, Thanks for your great job. I have a little question.
I reproduced the SYMNet on the OASIS DataSet, and save the flow field by 
![image](https://user-images.githubusercontent.com/69455175/200160945-4793c54d-af66-4c2a-91dd-36a6a99b1062.png)
I compute the number of non-positive Jacobian determinant and it is 100, which is very low and perfect. I also reproduced the Elastic_SyN method, and its number of non-positive Jacobian determinant is 1200; Then I visualize the deformed grid on this two methods of a case, it looks like that the deformed grid if SyN is more smoother, Is there any problem in my understanding? 
![image](https://user-images.githubusercontent.com/69455175/200161172-f170ede2-3018-4bf2-9114-c4ae07531225.png)
Thank you very much!!

**Comment by cwmok** [comment]
Hi @xiaorugao999, 

The grid from SYMNet is not as smooth as SyN for 2 main reasons: 
1) SYMNet estimates the **dense velocity field** while SyN estimates the sparse grid (**grid with control points**). Ideally, SYMNet allows a higher degree of freedom and is able to deal with "local" deformation.

2) The smoothness regularization of SYMNet may not be the same as SyN. If you prefer smoother solutions, you can increase the value of "--smooth" during training.

If you want to manipulate the smoothness of the solution during **_inference time_**, feel free to check out our latest [conditional LapIRN method](https://github.com/cwmok/Conditional_LapIRN). Conditional LapIRN takes the weight of the smoothness regularization as input and is able to compute deformation fields with arbitrary strength of smoothness.

**Comment by xiaorugao999** [comment]
I see. Thank you very much! I will learn from the latest conditional LapIRN method.
