### ISSUE TITLE
About the number of non-positive Jacobian determinant

### ISSUE THREAD

**Issue by Zhenyu-040314** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#18]
Hi, @cwmok, Thanks for your great job. I have a little question.
I reproduced the SYMNet on the OASIS DataSet, and I compute the number of non-positive Jacobian determinant.
But the number of non-positive Jacobian determinant is too large as shown below：
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/a81e9794-42ae-437a-869c-3c6dc4a834a3)

![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/d39aa165-a2fb-48af-951d-bd9d9dc2a2a3)

I don't know what's wrong and would appreciate your help!
Looking forward to your reply！

**Comment by cwmok** [comment]
Hi @zhenyu202020,
Which `Jacobian_determinant` function are you using? I guess the problem is in the `Jacobian_determinant`. Because for any identity deformation (empty displacement), the Jacobian determinant should be 1 ("after *-1 should be -1), but your function returns 0. Perhaps you should add the identity grid to the `F_BA` before using this function.

**Comment by Zhenyu-040314** [comment]
Thank you very much for your reply!
I have changed the calculation function and added the identity grid as follows, but still have the problem.
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/6b5dc5f9-370d-4b0f-b2f8-ecb324f23612)
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/56063bca-be4b-4db7-8eea-fe6a66c1c620)
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/bf3560cf-2388-4f7e-b536-b2ccca915404)
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/383a3c22-130e-4f59-a8ba-952ddb280a02)
I've tested 20 consecutive numbers and they're all zero.
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/42c6f265-9fb5-41a5-850b-96918ef149c9)

**Comment by cwmok** [comment]
Could you use `F_BA*0.0` as input for the Jaco function to see if the function works properly or not?

**Comment by cwmok** [comment]
I see the problem. The "F.relu" is an inplace operation. Try removing the "F.relu" operation.

**Comment by Zhenyu-040314** [comment]
As you said we used  F_BA*0.0 as input, and the results are shown below:
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/833132f1-3903-4412-9bbb-2a7715023991)
I've removed the "F.relu" operation, but there is still a problem
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/22653291-7622-4553-9af5-78ea4c6c1872)
I've tested 20 consecutive numbers and they're still all zero.
![image](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/assets/74998993/c0fafd6a-9edb-4b8d-8b8b-1763681467f2)

**Comment by cwmok** [comment]
The result is correct now. You can see most values in `neg_Jet` are close to 1. 
Since this method is a diffeomorphic method, you will observe 0 voxels with negative Jdet for most of the cases.

If you prefer a non-smooth solution, you can fine-tune the weights of smoothness and Jaco regularization in the training.

**Comment by Zhenyu-040314** [comment]
Thank you very much for the patient answers! This helps a lot!
