### ISSUE TITLE
Thank you for providing the code, can you expose the preprocessed dataset

### ISSUE THREAD

**Issue by luoyi1hao** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#2]
Looking forward to your reply. Thank you very much.

**Comment by cwmok** [comment]
In our paper, we use a publicly available dataset (OASIS), but we don't have the right to redistribute it. If you are interested in the preprocessed dataset, you may download it via https://www.oasis-brains.org/ (make sure you download the preprocessed version and you still need to further preprocess it, e.g. center cropping/changing the orientation). An example of the preprocessed data is provided in the "Data" folder in this repository.

**Comment by luoyi1hao** [comment]
Thank you very much for your help. I'm sorry to ask you the basic question.I have successfully downloaded part of the data set. Whether norm. MGZ and ASEG.mgz under mri/ folder respectively represent the image and segmentation that you will further process before. Can further pre-processing code be provided?

**Comment by luoyi1hao** [comment]
Thank you very much for your help. I'm sorry to ask you the basic question.I have successfully downloaded part of the data set. Whether norm. mgz and aseg.mgz under mri/ folder respectively represent the image and segmentation that you will further process before. Can further pre-processing code be provided?

**Comment by cwmok** [comment]
Currently, we have no plan to publish the code for pre-processing. If you want to try our SYMNet, you could resize/crop the pre-processed data using Numpy and NiBabel. As long as your GPU has enough memory, you are good to go.

**Comment by luoyi1hao** [comment]
Thank you very much for your help.
