### ISSUE TITLE
Thanks again for your help. Whether the resize /crop operation is for mri/norm.mgz or mri/brain.mgz?

### ISSUE THREAD

**Issue by luoyi1hao** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#3]
Thank you for a job well done. : )

**Comment by cwmok** [comment]
I guess you are talking about the OASIS dataset (the Freesurfer version). In my own experience, I first apply the affine normalization on norm.mgz and then check the orientation of each brain scan. Finally, I crop the normalized brain scan using NiBabel and Numpy. For details, you may refer to the documentation in the Freesurfer wiki here: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferWiki. They provide plenty of examples and you may want to look at it.

**Comment by luoyi1hao** [comment]
Thanks for your help. I'm mostly confused by affine normalization. Because I didn't find it in Freesurfer's recon-all command. I only saw the following similar information. Can it be understood that tools such as FSL or ANT are used for affine registration of images.
![Z49LR_8J4PV)}6 )W3J6)ZB](https://user-images.githubusercontent.com/49618455/99936016-1035aa80-2d9d-11eb-9b2c-1b6b319cee46.png)

**Comment by cwmok** [comment]
The Talairach transform computation is used for affine normalization in my pre-processing pipeline. I didn't use FSL or ANT in my pre-processing pipeline. Also, if you have difficulties in affine normalization, I suggest you also look at this repository: https://github.com/cwmok/LapIRN. We proposed a large deformation image registration method that can overcome large initial misalignment. You can use your raw data and give it a try.

**Comment by luoyi1hao** [comment]
Ok, I understand. Thank you for your help and your excellent work.

**Comment by luoyi1hao** [comment]
Sorry to bother you again. Previously I thought affine regularization(the Talairach transform) was used by default for norm.mgz and aseg.mgz on the OASIS dataset (the Freesurfer version).  So now I should use mri/talairach.xfm to transform norm.mgz and aseg.mgz, right?  
![image](https://user-images.githubusercontent.com/49618455/100039992-65c39300-2e41-11eb-9b8d-c625e43f4f3d.png)

**Comment by cwmok** [comment]
Yes, you are right.

**Comment by luoyi1hao** [comment]
Thank you for your quick reply. We used the following command (mri_convert norm.mgz --apply_transform talairach.xfm norm_affine.nii.mgz)
But the size of the image was reduced to 172, 220, 156. And it's going to rotate. Has this ever happened to you?

**Comment by cwmok** [comment]
I think it is normal. You can compare your preprocessed data with the testing scans I uploaded in this repository.
